
import java.awt.Graphics;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach
 */
public class SnapProto extends javax.swing.JFrame {

    /**
     * Creates new form SnapProto
     */
    public SnapProto() {
        initComponents();
        radioGroup.add(radio5);
        radioGroup.add(radio4);
        radioGroup.add(radio3A);
        radioGroup.add(radio3B);
        radioGroup.add(radio2);
        
        building5.setVisible(false);
        building4.setVisible(false);
        building3A.setVisible(false);
        building3B.setVisible(false);
        building2.setVisible(false);
        
        checkBuildings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        grid = new javax.swing.JPanel();
        building5 = new javax.swing.JPanel();
        building4 = new javax.swing.JPanel();
        building3A = new javax.swing.JPanel();
        building3B = new javax.swing.JPanel();
        building2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        radio5 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio3A = new javax.swing.JRadioButton();
        radio3B = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        rotateButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grid.setBackground(new java.awt.Color(255, 255, 255));
        grid.setPreferredSize(new java.awt.Dimension(200, 200));
        grid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gridMousePressed(evt);
            }
        });
        grid.setLayout(null);

        building5.setBackground(java.awt.Color.red);
        building5.setName("");
        building5.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout building5Layout = new javax.swing.GroupLayout(building5);
        building5.setLayout(building5Layout);
        building5Layout.setHorizontalGroup(
            building5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        building5Layout.setVerticalGroup(
            building5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        grid.add(building5);
        building5.setBounds(50, 36, 100, 20);

        building4.setBackground(new java.awt.Color(255, 200, 0));
        building4.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout building4Layout = new javax.swing.GroupLayout(building4);
        building4.setLayout(building4Layout);
        building4Layout.setHorizontalGroup(
            building4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        building4Layout.setVerticalGroup(
            building4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        grid.add(building4);
        building4.setBounds(70, 62, 80, 20);

        building3A.setBackground(new java.awt.Color(0, 255, 0));
        building3A.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout building3ALayout = new javax.swing.GroupLayout(building3A);
        building3A.setLayout(building3ALayout);
        building3ALayout.setHorizontalGroup(
            building3ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        building3ALayout.setVerticalGroup(
            building3ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        grid.add(building3A);
        building3A.setBounds(70, 88, 60, 20);

        building3B.setBackground(java.awt.Color.blue);
        building3B.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout building3BLayout = new javax.swing.GroupLayout(building3B);
        building3B.setLayout(building3BLayout);
        building3BLayout.setHorizontalGroup(
            building3BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        building3BLayout.setVerticalGroup(
            building3BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        grid.add(building3B);
        building3B.setBounds(50, 114, 60, 20);

        building2.setBackground(new java.awt.Color(255, 175, 175));
        building2.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout building2Layout = new javax.swing.GroupLayout(building2);
        building2.setLayout(building2Layout);
        building2Layout.setHorizontalGroup(
            building2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        building2Layout.setVerticalGroup(
            building2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        grid.add(building2);
        building2.setBounds(60, 140, 40, 20);

        jPanel2.setBackground(java.awt.Color.red);
        jPanel2.setName("");
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 200, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.setBackground(java.awt.Color.blue);
        jPanel5.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 175, 175));
        jPanel6.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        radio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio4ActionPerformed(evt);
            }
        });

        radio3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio3BActionPerformed(evt);
            }
        });

        rotateButton.setText("Rotate");
        rotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateButtonActionPerformed(evt);
            }
        });

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(removeButton)
                                .addComponent(rotateButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio5)
                            .addComponent(radio2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radio3A, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radio3B, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(radio4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(continueButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radio5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radio4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio3A)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio3B))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio2)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio3BActionPerformed

    private void radio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio4ActionPerformed

    private void gridMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridMousePressed
        int x = (evt.getX()/20)*20;
        int y = (evt.getY()/20)*20;
        
        if(radio5.isSelected())
        {
            building5.setLocation(x, y);
            if(!building5.isVisible())
                building5.setVisible(true);
        }
        if(radio4.isSelected())
        {
            building4.setLocation(x, y);
            if(!building4.isVisible())
                building4.setVisible(true);
        }
        if(radio3A.isSelected())
        {
            building3A.setLocation(x, y);
            if(!building3A.isVisible())
                building3A.setVisible(true);
        }
        if(radio3B.isSelected())
        {
            building3B.setLocation(x, y);
            if(!building3B.isVisible())
                building3B.setVisible(true);
        }
        if(radio2.isSelected())
        {
            building2.setLocation(x, y);
            if(!building2.isVisible())
                building2.setVisible(true);
        }
        
        checkBuildings();
        this.repaint();
    }//GEN-LAST:event_gridMousePressed

    private void rotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateButtonActionPerformed
        if(radio5.isSelected())
            building5.setSize(building5.getHeight(), building5.getWidth());
        else if(radio4.isSelected())
            building4.setSize(building4.getHeight(), building4.getWidth());
        else if(radio3A.isSelected())
            building3A.setSize(building3A.getHeight(), building3A.getWidth());
        else if(radio3B.isSelected())
            building3B.setSize(building3B.getHeight(), building3B.getWidth());
        else if(radio2.isSelected())
            building2.setSize(building2.getHeight(), building2.getWidth());
        else
            return;
        
        this.repaint();
    }//GEN-LAST:event_rotateButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_continueButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if(radio5.isSelected())
        {
            building5.setVisible(false);
        }
        else if(radio4.isSelected())
        {
            building4.setVisible(false);
        }
        else if(radio3A.isSelected())
        {
            building3A.setVisible(false);
        }
        else if(radio3B.isSelected())
        {
            building3B.setVisible(false);
        }
        else if(radio2.isSelected())
        {
            building2.setVisible(false);
        }
        else
            return;
        
        this.repaint();
        checkBuildings();
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
   private void drawGrid()
   {
      Graphics g = grid.getGraphics();
      int panel_width = grid.getWidth();
      int panel_height = grid.getHeight();
      int step_x = panel_width / 10;
      int step_y = panel_height / 10;

      for (int i = 1; i < 10; i ++)
      {
         g.drawLine(i * step_x, 0, i * step_x, panel_height);
         g.drawLine(0, i * step_y, panel_width, i * step_y);
      }
   }
   
   private void checkBuildings()
   {
       if(building5.isVisible()&&building4.isVisible()&&building3A.isVisible()&&building3B.isVisible()&&building2.isVisible())
           continueButton.setEnabled(true);
       else
           continueButton.setEnabled(false);
   }
  
   @Override
   public void paint(Graphics g)
   {
      super.paint(g);
      drawGrid();
   }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnapProto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnapProto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnapProto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnapProto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SnapProto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel building2;
    private javax.swing.JPanel building3A;
    private javax.swing.JPanel building3B;
    private javax.swing.JPanel building4;
    private javax.swing.JPanel building5;
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel grid;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3A;
    private javax.swing.JRadioButton radio3B;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton rotateButton;
    // End of variables declaration//GEN-END:variables
}
